In [1]:
import pandas as pd

In [2]:
pd_merged = pd.read_csv('merged_data.csv')
display(pd_merged)

,Country,Year,Status,Population,Hepatitis B,Measles,Polio,Diphtheria,HIV/AIDS,infant deaths,...,thinness 1-19 years,Alcohol,Schooling,Life expectancy,Country Code,Indicator Name,Indicator Code,Value,Country Code,GDP
0,Afghanistan,2015,Developing,33736494.0,65.0,1154,6.0,65.0,0.1,62,...,17.2,0.01,10.1,65.0,AFG,Population ages 15-64 (% of total population),SP.POP.1564.TO.ZS,51.802078,AFG,1886.692977
1,Afghanistan,2015,Developing,33736494.0,65.0,1154,6.0,65.0,0.1,62,...,17.2,0.01,10.1,65.0,AFG,Population ages 0-14 (% of total population),SP.POP.0014.TO.ZS,45.792106,AFG,1886.692977
2,Afghanistan,2015,Developing,33736494.0,65.0,1154,6.0,65.0,0.1,62,...,17.2,0.01,10.1,65.0,AFG,Unemployment,total (% of total labor force) (modeled ILO e...,7.910000,AFG,1886.692977
3,Afghanistan,2015,Developing,33736494.0,65.0,1154,6.0,65.0,0.1,62,...,17.2,0.01,10.1,65.0,AFG,Unemployment,male (% of male labor force) (modeled ILO est...,7.340000,AFG,1886.692977
4,Afghanistan,2015,Developing,33736494.0,65.0,1154,6.0,65.0,0.1,62,...,17.2,0.01,10.1,65.0,AFG,Unemployment,female (% of female labor force) (modeled ILO...,10.306000,AFG,1886.692977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459195,Zimbabwe,2000,Developing,12222251.0,79.0,1483,78.0,78.0,43.5,24,...,11.0,1.68,9.8,46.0,ZWE,Literacy rate,adult female (% of females ages 15 and above),NaN,ZWE,2344.271146
459196,Zimbabwe,2000,Developing,12222251.0,79.0,1483,78.0,78.0,43.5,24,...,11.0,1.68,9.8,46.0,ZWE,Literacy rate,youth total (% of people ages 15-24),NaN,ZWE,2344.271146
459197,Zimbabwe,2000,Developing,12222251.0,79.0,1483,78.0,78.0,43.5,24,...,11.0,1.68,9.8,46.0,ZWE,Literacy rate,youth male (% of males ages 15-24),NaN,ZWE,2344.271146
459198,Zimbabwe,2000,Developing,12222251.0,79.0,1483,78.0,78.0,43.5,24,...,11.0,1.68,9.8,46.0,ZWE,Literacy rate,youth (ages 15-24),NaN,ZWE,2344.271146
459199,Zimbabwe,2000,Developing,12222251.0,79.0,1483,78.0,78.0,43.5,24,...,11.0,1.68,9.8,46.0,ZWE,Literacy rate,youth female (% of females ages 15-24),NaN,ZWE,2344.271146